version: '3.9'

services:
  nginx:
    build: 
      context: .
      dockerfile: nginx.dockerfile
    ports: 
      - 80:80
      - 443:443
    volumes:
      - ./wordpress:/var/www/html:delegated
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: secret
    volumes: 
      - ./mysql:/var/lib/mysql
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./wordpress:/var/www/html:delegated
    image: php:7.4-fpm-alpine